workspace = 10, default:true, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:eDP-1
workspace = 1, default:true, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-3
workspace = 2, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-3
workspace = 3, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-3
workspace = 4, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-3
workspace = 5, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-3
workspace = 6, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-6
workspace = 7, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-6
workspace = 7, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-6
workspace = 8, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-6
workspace = 9, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-6
#workspace = 10, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:desc:Iiyama North America PL3493WQ 1213532400158

